name: Update Versions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config advice.detachedHead false
    - name: Unshallow Clone
      run: |
        head=$(git rev-parse HEAD)
        cd class_public
        git remote set-branches origin '*'
        git fetch --unshallow --tags origin '+refs/heads/*:refs/heads/*'
        git checkout master
        branches=$(git branch --format='%(refname:short)')
        tags=$(git tag)
        cd ..

        echo "head: $(echo ${head})"
        echo "::set-env name=head::$(echo ${head})"

        echo "branches: $(echo ${branches})"
        echo "::set-env name=branches::$(echo ${branches})"

        echo "tags: $(echo ${tags})"
        echo "::set-env name=tags::$(echo ${tags})"
    - name: Update Branches
      run: |
        for b in ${branches}; do
          echo "branch ${b}"
          git checkout -f ${b} || git checkout -b ${b}
          git reset --hard ${head}
          git submodule set-branch --branch ${b} class_public
          git submodule update --remote
          git diff --quiet || git commit -am "branch ${b}"
        done
        git push -f --all origin
    - name: Update Tags
      run: |
        for t in ${tags}; do
          echo "tag ${t}"
          git checkout -f ${head}
          git reset --hard ${head}
          cd class_public
          git checkout ${t}
          cd ..
          git diff --quiet || git commit -am "tag ${t}"
          git tag -f ${t}
        done
        git push -f --tags
