name: Update Versions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config advice.detachedHead false
    - name: Unshallow Clone
      run: |
        head=$(git rev-parse HEAD)
        cd class_public
        git remote set-branches origin '*'
        git fetch --unshallow --tags origin '+refs/heads/*:refs/heads/*'
        git checkout master
        branches=$(git branch --format='%(refname:short)')
        tags=$(git tag)
        cd ..

        echo "head: $(echo ${head})"
        echo "::set-env name=head::$(echo ${head})"

        echo "branches: $(echo ${branches})"
        echo "::set-env name=branches::$(echo ${branches})"

        echo "tags: $(echo ${tags})"
        echo "::set-env name=tags::$(echo ${tags})"
    - name: Update Branches
      run: |
        for b in ${branches}; do
          (git checkout -qf ${b} 2> /dev/null && echo "checkout ${b}") || (git branch -qf ${b} ${head} && git checkout -qf ${b} && echo "branch ${b}")
          prev=$(git rev-parse HEAD)
          git reset -q --hard ${head}
          git submodule -q set-branch --branch ${b} class_public
          git submodule -q update --remote
          git diff --quiet || git commit -qam "branch ${b}"
          git diff --quiet ${prev} && git reset -q --hard ${prev} && echo "no change"
        done
        git push -f --all origin
    - name: Update Tags
      run: |
        for t in ${tags}; do
          (git checkout -qf ${t} 2> /dev/null && echo "checkout ${t}") || (git checkout -qf ${head} && echo "tag ${t}")
          prev=$(git rev-parse HEAD)
          git reset -q --hard ${head}
          cd class_public && git checkout -qf ${t} && cd ..
          git diff --quiet || git commit -qam "tag ${t}"
          git diff --quiet ${prev} && git reset -q --hard ${prev} && echo "no change"
          git tag -f ${t}
        done
        git push -f --tags origin
